export { createDaemonClient } from './client';
export type { ConnectionStatus, DaemonClient, DaemonClientOptions } from './client';
export { useDaemonStream } from './useDaemonStream';
export { toFeedMessage } from './normalize';
export { discover, resetDiscovery } from './discovery';
export { listChannels, joinChannel, leaveChannel, getCapabilities, DaemonUnreachableError } from './api';
export { useChannels } from './useChannels';
export type { ChannelsStatus } from './useChannels';
export { useCapabilities } from './useCapabilities';
export type { CapabilitiesStatus } from './useCapabilities';
export { startTwitchDevice, twitchDeviceStatus, startKickAuth, kickAuthStatus, pollSession, isTerminal } from './auth';
export { listProfiles, createProfile, activateProfile } from './profiles';
export { useProfiles } from './useProfiles';
export type { ProfilesStatus } from './useProfiles';
export { previewSend, sendMessage } from './send';
