export { createDaemonClient } from './client';
export type { ConnectionStatus, DaemonClient, DaemonClientOptions } from './client';
export { useDaemonStream } from './useDaemonStream';
export type { StreamHandlers } from './useDaemonStream';
export { toFeedMessage, channelKey } from './normalize';
export { discover, resetDiscovery } from './discovery';
export { listChannels, joinChannel, leaveChannel, getCapabilities, DaemonUnreachableError } from './api';
export { useChannels } from './useChannels';
export type { ChannelsStatus } from './useChannels';
export { useCapabilities } from './useCapabilities';
export type { CapabilitiesStatus } from './useCapabilities';
export { useStats } from './useStats';
export type { ChannelStats } from './useStats';
export { useStreams, listStreams } from './streams';
export { listFilters, saveFilters } from './filters';
export { listMethods, setMethod } from './connections';
export { listAccounts, disconnectAccount } from './accounts';
export { getAuthConfig, setAuthConfig } from './authConfig';
export { listEmotes, useEmotes } from './emotes';
export { startTwitchDevice, twitchDeviceStatus, startKickAuth, kickAuthStatus, pollSession, isTerminal } from './auth';
export { listProfiles, createProfile, activateProfile } from './profiles';
export { useProfiles } from './useProfiles';
export type { ProfilesStatus } from './useProfiles';
export { previewSend, sendMessage } from './send';
export { listHeld, approveHeld, denyHeld, useHeld } from './held';
export type { HeldQueue } from './held';
export { searchMessages, getHistory } from './search';
export type { SearchParams } from './search';
export { getIntegration, useIntegration } from './integration';
export type { IntegrationReport, IntegrationFeature } from './integration';
export { listTokens, mintToken, revokeToken } from './tokens';
export { listThemes, importTheme, exportTheme, deleteTheme } from './themes';
export { listModels, getIntelConfig, setIntelConfig, askStream } from './intel';
export { getHostedStatus, register, login, logout, getMe } from './account';
export { listPlugins, enablePlugin, disablePlugin, installPlugin, uninstallPlugin } from './plugins';
export type { PluginInfo } from './plugins';
export { listConversations, getConversation, saveConversation, deleteConversation, generateTitleStream } from './conversations';
export type { ConversationSummary, ConversationDetail, SaveConversationPayload } from './conversations';
export type { VirtaUser, HostedStatus } from './account';
export { HostedAuthProvider, useHostedAuth, useIsGuest } from './hostedAuth';
export type { HostedAuthState } from './hostedAuth';
export { loadGuestChannels, clearGuestChannels } from './localChannels';
